#!/usr/bin/env python3
"""
从浏览器自动导出 Moodle cookies

要求：pip install browser-cookie3
"""

import os
import sys

try:
    import browser_cookie3
except ImportError:
    print("错误：需要安装 browser-cookie3")
    print("运行：pip install browser-cookie3")
    sys.exit(1)

DOMAIN = 'keats.kcl.ac.uk'
OUTPUT_FILE = '/Users/linqilan/CodingProjects/Cookies.txt'

def export_cookies_from_browser(browser_name='chrome'):
    """从指定浏览器导出 cookies"""

    print(f"正在从 {browser_name} 导出 cookies...")

    try:
        if browser_name == 'chrome':
            cj = browser_cookie3.chrome(domain_name=DOMAIN)
        elif browser_name == 'firefox':
            cj = browser_cookie3.firefox(domain_name=DOMAIN)
        elif browser_name == 'edge':
            cj = browser_cookie3.edge(domain_name=DOMAIN)
        elif browser_name == 'safari':
            cj = browser_cookie3.safari(domain_name=DOMAIN)
        else:
            print(f"不支持的浏览器：{browser_name}")
            return False

        # 转换为列表以便计数和过滤
        cookies_list = []
        for cookie in cj:
            # 只保存 keats.kcl.ac.uk 和 Microsoft SSO 相关的 cookies
            if any(domain in cookie.domain for domain in [DOMAIN, 'microsoftonline.com']):
                cookies_list.append(cookie)

        if not cookies_list:
            print(f"❌ 未找到 {DOMAIN} 的 cookies")
            print(f"   请确保：")
            print(f"   1. 已在 {browser_name} 中登录 {DOMAIN}")
            print(f"   2. {browser_name} 正在运行或最近使用过")
            return False

        # 备份现有文件
        if os.path.exists(OUTPUT_FILE):
            backup_file = OUTPUT_FILE + '.backup'
            os.rename(OUTPUT_FILE, backup_file)
            print(f"✅ 已备份现有文件到: {backup_file}")

        # 写入 Netscape cookie 格式
        with open(OUTPUT_FILE, 'w') as f:
            f.write('# Netscape HTTP Cookie File\n')
            f.write(f'# Exported from {browser_name} browser\n')
            f.write(f'# Domain: {DOMAIN}\n')
            f.write('# This file is generated by export_browser_cookies.py\n\n')

            for cookie in cookies_list:
                # Netscape cookie format:
                # domain, flag, path, secure, expiration, name, value
                domain = cookie.domain
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.path
                secure = 'TRUE' if cookie.secure else 'FALSE'
                expires = cookie.expires if cookie.expires else 0
                name = cookie.name
                value = cookie.value

                f.write(f'{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n')

        print(f"✅ 成功导出 {len(cookies_list)} 个 cookies 到: {OUTPUT_FILE}")

        # 显示关键 cookies
        print("\n关键 Cookies:")
        for cookie in cookies_list:
            if cookie.name in ['MoodleSession', 'ApplicationGatewayAffinity', 'MOODLEID1_']:
                print(f"  ✓ {cookie.name}: {cookie.value[:30]}...")

        return True

    except Exception as e:
        print(f"❌ 导出失败: {e}")
        return False

def test_cookies():
    """测试导出的 cookies 是否有效"""
    print("\n正在测试 cookies 有效性...")

    try:
        import requests

        session = requests.Session()

        # 加载 cookies
        from http.cookiejar import MozillaCookieJar
        cookie_jar = MozillaCookieJar(OUTPUT_FILE)
        cookie_jar.load(ignore_discard=True, ignore_expires=True)
        session.cookies = cookie_jar

        # 测试访问
        response = session.get('https://keats.kcl.ac.uk/', timeout=10)

        if 'login/logout.php' in response.text:
            print("✅ Cookies 有效！已成功认证")
            return True
        elif 'login/index.php' in response.url:
            print("❌ Cookies 无效，被重定向到登录页")
            print("   请确保在浏览器中已登录 keats.kcl.ac.uk")
            return False
        else:
            print("⚠️  无法确定 cookies 状态")
            print(f"   响应 URL: {response.url}")
            return False

    except Exception as e:
        print(f"⚠️  测试失败: {e}")
        return False

def main():
    print("=" * 80)
    print("Moodle Browser Cookies 导出工具")
    print("=" * 80)

    # 尝试自动检测浏览器
    browsers_to_try = ['chrome', 'edge', 'firefox', 'safari']

    success = False
    for browser in browsers_to_try:
        print(f"\n尝试从 {browser} 导出...")
        if export_cookies_from_browser(browser):
            success = True
            break

    if not success:
        print("\n" + "=" * 80)
        print("❌ 所有浏览器导出均失败")
        print("\n请手动导出 cookies：")
        print("1. 安装浏览器扩展 'Get cookies.txt LOCALLY'")
        print("2. 在浏览器中登录 https://keats.kcl.ac.uk")
        print("3. 点击扩展图标，导出 cookies")
        print(f"4. 保存到: {OUTPUT_FILE}")
        print("=" * 80)
        sys.exit(1)

    # 测试 cookies
    test_cookies()

    print("\n" + "=" * 80)
    print("下一步：运行 moodle-dl 下载 kalvidres 视频")
    print("=" * 80)
    print(f"cd /Users/linqilan/CodingProjects/Moodle-DL")
    print(f"moodle-dl --path /Users/linqilan/CodingProjects")
    print("=" * 80)

if __name__ == '__main__':
    main()
