# -*- coding: utf-8 -*-
"""
Tests pinning the contracts for the 4 problems user raised in
/Volumes/Untitled/test3 (4CCS1ISE Introduction to Software
Engineering, Section 2: Requirements Analysis, UML and Use Case
Diagrams).

These tests are RED (failing) until the corresponding fixes are
implemented. They document the EXPECTED behavior:

  Problem 1: Singleton description file inside *01* label folder
             should be flattened. PARTIALLY FIXED in commit
             155be82 (label modules with no attachments go
             flat). Test coverage exists in
             test_page_label_url_flattening.py.

  Problem 2: Table of Contents.html uses cm_id-based hrefs
             (e.g. <a href="691954/index.html">) but the actual
             folder is *07* 4. UML/. The TOC must use the actual
             on-disk folder name so clicking the link works.

  Problem 3: The parent print book HTML
             (Week 2 - Requirements Analysis.html) has
             <source src="2. Week Overview/Video.mp4"> but the
             actual folder is *01* 2. Week Overview/. The src
             must use the actual on-disk folder name so the
             video renders.

  Problem 4: cookie_mod and url-description-book files in a book
             chapter should share the chapter's folder (and
             hence the chapter's *NN* prefix), not get their own
             folder with a separate (conflicting) position.

             In the DB:
               file_id=94, book, index.html: position 1
               file_id=95, cookie_mod-kalvidres, Kaltura: position 0
               file_id=98, cookie_mod-kalvidres, video: position 0
               file_id=99, url-description-book, https://...: position 0

             file_id=95, 98, 99 all have module_id = 7342416
             (same as the chapter), but get position 0 from
             the non-book counter instead of inheriting the
             chapter's position from the book counter.
"""

import os
import sys
from unittest.mock import MagicMock

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# =========================================================================
# Helpers
# =========================================================================
def _make_book():
    """Build a BookMod with mocked dependencies."""
    from moodle_dl.moodle.mods.book import BookMod
    from moodle_dl.config import ConfigHelper

    config = MagicMock()
    book = BookMod.__new__(BookMod)
    book.config = config
    return book


def _make_lti_src(entry_id: str) -> str:
    """Build a kaltura LTI iframe src URL with the given entry_id."""
    return (
        f'https://keats.kcl.ac.uk/filter/kaltura/lti_launch.php'
        f'?courseid=0&height=402&width=608&withblocks=0'
        f'&source=https://kaf.keats.kcl.ac.uk/browseandembed/index/'
        f'media/entryid/{entry_id}/showDescription/false/showTitle/'
        f'false/showTags/false/showDuration/false/showOwner/'
        f'false/showUploadDate/false/playerSkin/42864872/'
    )


# =========================================================================
# Problem 2: TOC must use actual on-disk folder names
# =========================================================================
class TestTableOfContentsUsesActualFolderNames:
    """The Table of Contents.html generated by book.py must use
    the actual on-disk folder name (with *NN* prefix) in href,
    not the cm_id-based href from Moodle's Print Book API.

    User report (test3):
      <a href="691954/index.html">UML</a>  ← broken
      <a href="*07* 4. UML/index.html">UML</a>  ← expected

    This test is RED until the fix is applied.
    """

    def test_toc_href_uses_cm_id_bug_pinned(self):
        """Pin the BUGGY behavior of create_ordered_index: it
        uses the cm_id-based href from book_toc, not the actual
        on-disk folder name.

        The actual fix should rewrite the href to use the
        chapter's on-disk folder name (with *NN* prefix).

        This test documents the bug. When the fix is in, this
        test should be updated to assert the correct behavior.
        """
        from moodle_dl.moodle.mods.book import BookMod

        book_toc = [
            {'title': 'UML', 'href': '691954/index.html', 'level': 0}
        ]
        toc_html = BookMod.create_ordered_index(BookMod.__new__(BookMod), book_toc)

        # Current buggy behavior: the cm_id-based href is used
        # Pin this so future changes are intentional.
        assert 'href="691954/index.html"' in toc_html, (
            f'Pre-fix: TOC uses cm_id-based href. '
            f'This is the bug we want to fix. Got: {toc_html!r}'
        )
        # The on-disk folder name (*07* 4. UML) should NOT be in
        # the TOC yet (the fix should add it).
        assert '*07* 4. UML/index.html' not in toc_html, (
            f'After fix, TOC should use on-disk folder name. '
            f'Got: {toc_html!r}'
        )

    def test_create_ordered_index_passes_chapter_on_disk_name(self):
        """The book module's create_ordered_index / TOC generation
        should use the chapter's on-disk folder name (with *NN*
        prefix) when generating href.

        Pinning contract: when given a chapter with on-disk folder
        name '*07* 4. UML', the TOC href should be '*07* 4. UML/index.html'.
        """
        # This test will be enabled after the fix.
        # For now, document the expected behavior.
        # When the fix is in: assert '*07* 4. UML/index.html' in toc_html
        pass


# =========================================================================
# Problem 3: Print book video src must use on-disk folder name
# =========================================================================
class TestPrintBookVideoSrcUsesOnDiskFolderName:
    """The print book HTML (Week 2 - Requirements Analysis, UML and
    Use Case Diagrams.html) has Kaltura iframes that get rewritten
    to HTML5 <video> tags. The src must use the on-disk folder
    name (with *NN* prefix), not the raw chapter folder name.

    User report (test3):
      <source src="2. Week Overview/Week Overview - Video.mp4">  ← broken
      <source src="*01* 2. Week Overview/Week Overview - Video.mp4">  ← expected

    This test is RED until the fix is applied.
    """

    def test_video_src_uses_raw_chapter_name_bug_pinned(self):
        """Pin the BUGGY behavior of _create_linked_print_book_html:
        the chapter_info dict (built by book.py:1428) has the raw
        chapter folder name (e.g. "2. Week Overview") without the
        *NN* prefix, so the video src in the HTML is wrong.

        This test documents the bug. When the fix is in (book.py
        should pass the on-disk folder name with *NN* prefix),
        this test will need to be updated to reflect the fix.
        """
        from moodle_dl.moodle.mods.book import BookMod
        book = _make_book()
        mapped_src = _make_lti_src('1_cka79uqg')
        html = f'<iframe class="kaltura-player-iframe" src="{mapped_src}"></iframe>'

        # Simulate what book.py:1428 ACTUALLY produces:
        # folder_name = chapter_folder_name (raw, no *NN* prefix)
        chapter_mapping = {
            '691952': {
                'folder_name': '2. Week Overview',  # raw chapter name
                'videos': [
                    {'entry_id': '1_cka79uqg', 'filename': 'Week Overview - Video (1_cka79uqg).mp4'},
                ],
            }
        }

        modified = book._create_linked_print_book_html(html, chapter_mapping)
        # Currently produces: "2. Week Overview/Week Overview - Video.mp4"
        # (the BUG). When fix is in, should produce "*01* 2. Week Overview/..."
        # Pin the bug so future changes are intentional.
        assert 'source src="2. Week Overview/Week Overview - Video (1_cka79uqg).mp4"' in modified, (
            f'Pre-fix: video src uses raw chapter name. '
            f'This is the bug we want to fix. Got: {modified!r}'
        )

    def test_video_src_uses_on_disk_folder_name_with_prefix(self):
        """When a chapter has position_in_section=0 (on-disk folder
        *01* 2. Week Overview), the video src should be
        *01* 2. Week Overview/Video.mp4, NOT 2. Week Overview/Video.mp4.
        """
        from moodle_dl.moodle.mods.book import BookMod
        book = _make_book()
        mapped_src = _make_lti_src('1_cka79uqg')
        html = f'<iframe class="kaltura-player-iframe" src="{mapped_src}"></iframe>'

        # The chapter_mapping should include the ON-DISK folder name
        # (with *NN* prefix), not the raw chapter name.
        chapter_mapping = {
            '691952': {  # cm_id
                'folder_name': '*01* 2. Week Overview',  # on-disk name
                'videos': [
                    {'entry_id': '1_cka79uqg', 'filename': 'Week Overview - Video (1_cka79uqg).mp4'},
                ],
            }
        }

        modified = book._create_linked_print_book_html(html, chapter_mapping)
        # The video src should use the on-disk folder name
        assert 'source src="*01* 2. Week Overview/Week Overview - Video (1_cka79uqg).mp4"' in modified, (
            f'Video src should use on-disk folder name *01* 2. Week Overview/, '
            f'got: {modified!r}'
        )
        # The buggy path should NOT be present
        assert 'source src="2. Week Overview/Week Overview - Video (1_cka79uqg).mp4"' not in modified, (
            f'Video src should NOT use raw chapter name (no *NN* prefix), '
            f'got: {modified!r}'
        )


# =========================================================================
# Problem 4: cookie_mod and url-description-book files should share
#            the parent book's position counter
# =========================================================================


# =========================================================================
# Problem 2: chapter_mapping folder_name should include *NN* prefix
# =========================================================================
class TestChapterMappingHasOnDiskFolderName:
    """When book.py builds chapter_mapping (the data structure
    passed to _create_linked_print_book_html), the folder_name
    should be the on-disk name (with *NN* prefix), not the raw
    chapter folder name.

    Real case (test3): book.py:303 sets
      'folder_name': chapter_folder_name
    where chapter_folder_name comes from _format_chapter_folder_name,
    which returns the raw chapter name (e.g. '2. Week Overview')
    WITHOUT the *NN* prefix.

    The actual on-disk folder is *02* 2. Week Overview/ (with prefix).

    This is the root cause of Problem 3 (videos don't render) and
    also affects Problem 2 (TOC links).
    """

    def test_format_chapter_folder_name_returns_raw_name(self):
        """Pin the current behavior of _format_chapter_folder_name:
        it returns the raw chapter name WITHOUT *NN* prefix.

        This is the root cause of Problems 2 and 3.
        """
        from moodle_dl.moodle.mods.book import BookMod
        # When chapter_number is set (Moodle's own numbering)
        result = BookMod._format_chapter_folder_name(
            chapter_title='Week Overview',
            chapter_number='1.1',
            fallback_index=0,
        )
        # Current behavior: returns '1.1 Week Overview' (no *NN* prefix)
        assert result == '1.1 Week Overview', (
            f'_format_chapter_folder_name returns raw chapter name. '
            f'This causes Problems 2 and 3. Got: {result!r}'
        )

    def test_format_chapter_folder_name_with_fallback(self):
        """Pin the current behavior with no chapter_number (uses
        fallback_index).
        """
        from moodle_dl.moodle.mods.book import BookMod
        result = BookMod._format_chapter_folder_name(
            chapter_title='Week Overview',
            chapter_number='',
            fallback_index=2,
        )
        # Current behavior: '02 - Week Overview' (no *NN* prefix)
        assert result == '02 - Week Overview', (
            f'_format_chapter_folder_name with fallback. Got: {result!r}'
        )


class TestCookieModAndUrlDescriptionBookShareBookPosition:
    """When a book chapter has cookie_mod (kaltura video) or
    url-description-book (external URL) sub-files, these sub-files
    should share the chapter's book-counter position, not get a
    separate non-book counter position.

    Real case (test3):
      Chapter 2 has:
        - index.html (book) → position 1 → folder *02*
        - kaltura video (cookie_mod-kalvidres) → position 0 (BUG)
        - webloc (url-description-book) → position 0 (BUG)

      Result: chapter 2's index.html is in *03* 2. Week Overview/
              and the videos are in *01* 2. Week Overview/
              (two separate folders with the same chapter name)

      Expected: all 3 files in the same folder
              *02* 2. Week Overview/ (or whatever the chapter's
              assigned position is)

    The fix: cookie_mod-kalvidres and url-description-book files
    inside a book chapter should use the book-counter (same as
    the chapter's index.html), not the non-book counter.
    """

    def test_cookie_mod_in_book_chapter_uses_book_counter(self):
        """cookie_mod-kalvidres file with module_id == book module_id
        should get position from the book counter, not the non-book
        counter.

        Real case (test3 DB):
          file_id=93, book, main HTML: position 0 (book counter, ok)
          file_id=94, book, index.html: position 1 (book counter, ok)
          file_id=95, cookie_mod-kalvidres, Kaltura: position 0  <- BUG
            Should be position 1 (same as chapter's index.html)
            so all chapter files end up in the same folder.

        Currently FAILS (RED) because the kaltura gets position 0
        from the non-book counter instead of inheriting the
        chapter's position from the book counter.
        """
        from moodle_dl.moodle.result_builder import ResultBuilder
        from moodle_dl.types import File, MoodleURL

        rb = ResultBuilder.__new__(ResultBuilder)
        rb.moodle_url = MoodleURL(use_http=False, domain='example.com', path='')
        rb.version = 2024100712
        rb.token = 'testtoken'
        rb.mod_plurals = {}

        # Simulate the file processing order from test3:
        # 1. Book main HTML (book, position 0)
        # 2. Book chapter 1 index.html (book, position 1)
        # 3. Book chapter 1 kaltura video (cookie_mod, position 1)
        book_main = File(
            module_id=7342416, section_id=1,
            section_name='Week 2',
            module_name='Week 2 - Requirements', module_modname='book',
            content_filepath='/',
            content_filename='Week 2 - Requirements.html',
            content_fileurl='https://example.com/main.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        chapter1_index = File(
            module_id=7342416, section_id=1,  # SAME module_id (book)
            section_name='Week 2',
            module_name='2. Week Overview', module_modname='book',
            content_filepath='/2. Week Overview/',
            content_filename='index.html',
            content_fileurl='https://example.com/2/index.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        chapter1_kaltura = File(
            module_id=7342416, section_id=1,  # SAME module_id (book)
            section_name='Week 2',
            module_name='2. Week Overview', module_modname='cookie_mod-kalvidres',
            content_filepath='/2. Week Overview/',
            content_filename='Week Overview - Video (1_cka79uqg).mp4',
            content_fileurl='https://example.com/video.mp4',
            content_type='cookie_mod',
            content_isexternalfile=True,
            content_filesize=1024000,
            content_timemodified=1700000000,
        )
        files = [book_main, chapter1_index, chapter1_kaltura]

        rb._assign_positions_to_files(files)

        # The kaltura should share the chapter's position (1)
        assert files[2].position_in_section == files[1].position_in_section, (
            f'cookie_mod sub-file should share book chapter position. '
            f'index.html position={files[1].position_in_section}, '
            f'kaltura position={files[2].position_in_section}. '
            f'The kaltura should be in the SAME folder as the chapter.'
        )
        # The book main HTML is position 0
        assert files[0].position_in_section == 0
        # The chapter index.html is position 1
        assert files[1].position_in_section == 1

    def test_url_description_book_in_book_chapter_uses_book_counter(self):
        """url-description-book file with module_id == book module_id
        should get position from the book counter, not the non-book
        counter.

        Same pattern as test_cookie_mod_in_book_chapter_uses_book_counter.
        """
        from moodle_dl.moodle.result_builder import ResultBuilder
        from moodle_dl.types import File, MoodleURL

        rb = ResultBuilder.__new__(ResultBuilder)
        rb.moodle_url = MoodleURL(use_http=False, domain='example.com', path='')
        rb.version = 2024100712
        rb.token = 'testtoken'
        rb.mod_plurals = {}

        book_main = File(
            module_id=7342416, section_id=1,
            section_name='Week 2',
            module_name='Week 2 - Requirements', module_modname='book',
            content_filepath='/',
            content_filename='Week 2 - Requirements.html',
            content_fileurl='https://example.com/main.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        chapter3_index = File(
            module_id=7342416, section_id=1,
            section_name='Week 2',
            module_name='3. Requirement Analysis', module_modname='book',
            content_filepath='/3. Requirement Analysis/',
            content_filename='index.html',
            content_fileurl='https://example.com/3/index.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        chapter3_url = File(
            module_id=7342416, section_id=1,  # SAME module_id (book)
            section_name='Week 2',
            module_name='3. Requirement Analysis', module_modname='url-description-book',
            content_filepath='/3. Requirement Analysis/',
            content_filename='ebookcentral proquest webloc',
            content_fileurl='https://ebookcentral.proquest.com/...',
            content_type='url_introfile',
            content_isexternalfile=True,
            content_filesize=0,
            content_timemodified=1700000000,
        )
        files = [book_main, chapter3_index, chapter3_url]

        rb._assign_positions_to_files(files)

        # The url should share the chapter's position (1)
        assert files[2].position_in_section == files[1].position_in_section, (
            f'url-description-book sub-file should share book chapter position. '
            f'index.html position={files[1].position_in_section}, '
            f'url position={files[2].position_in_section}'
        )

    def test_cookie_mod_standalone_uses_non_book_counter(self):
        """cookie_mod that's NOT part of a book chapter (different
        module_id) should use the non-book counter, not the book
        counter. This is the existing behavior — we just want to
        pin that we don't break it.
        """
        from moodle_dl.moodle.result_builder import ResultBuilder
        from moodle_dl.types import File, MoodleURL

        rb = ResultBuilder.__new__(ResultBuilder)
        rb.moodle_url = MoodleURL(use_http=False, domain='example.com', path='')
        rb.version = 2024100712
        rb.token = 'testtoken'
        rb.mod_plurals = {}

        # Standalone cookie_mod (not part of a book)
        standalone_kaltura = File(
            module_id=999, section_id=1,  # different module_id
            section_name='General',             module_name='Standalone Video', module_modname='cookie_mod-kalvidres',
            content_filepath='/',
            content_filename='Video.mp4',
            content_fileurl='https://example.com/video.mp4',
            content_type='cookie_mod',
            content_isexternalfile=True,
            content_filesize=1024000,
            content_timemodified=1700000000,
        )
        # Standalone resource
        standalone_resource = File(
            module_id=1000, section_id=1,
            section_name='General',             module_name='Standalone Resource', module_modname='resource',
            content_filepath='/',
            content_filename='lecture.pdf',
            content_fileurl='https://example.com/l.pdf',
            content_type='resource_file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        files = [standalone_kaltura, standalone_resource]

        rb._assign_positions_to_files(files)

        # Both should have unique positions (0 and 1)
        assert files[0].position_in_section == 0
        assert files[1].position_in_section == 1


# =========================================================================
# Book module folder vs file path: cookie_mod should be in same folder
# =========================================================================
class TestCookieModInsideBookChapterFolder:
    """Verify that the on-disk folder structure has the cookie_mod
    files in the SAME folder as the chapter's index.html.
    """

    def test_cookie_mod_and_chapter_share_same_gen_path(self):
        """Both the chapter's index.html AND the chapter's cookie_mod
        video should be saved in the same on-disk folder
        (chapter's *NN* folder, e.g. *02* 2. Week Overview/).
        """
        from moodle_dl.downloader.task_file_ops import TaskFileOps
        from moodle_dl.types import File, Course

        course = Course(_id=1, fullname='Test Course')
        ops = TaskFileOps(MagicMock())

        # Chapter index.html
        index_html = File(
            module_id=7342416, section_id=1,
            section_name='Week 2',             module_name='2. Week Overview', module_modname='book',
            content_filepath='/2. Week Overview/',
            content_filename='index.html',
            content_fileurl='https://example.com/2/index.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        index_html.position_in_section = 1  # chapter's position in book
        setattr(index_html, '_module_has_attachments', True)
        setattr(index_html, '_in_module_folder', True)

        # Chapter's cookie_mod video
        kaltura = File(
            module_id=7342416, section_id=1,
            section_name='Week 2',             module_name='2. Week Overview', module_modname='cookie_mod-kalvidres',
            content_filepath='/2. Week Overview/',
            content_filename='Week Overview - Video.mp4',
            content_fileurl='https://example.com/video.mp4',
            content_type='cookie_mod',
            content_isexternalfile=True,
            content_filesize=1024000,
            content_timemodified=1700000000,
        )
        kaltura.position_in_section = 1  # SAME position as chapter
        setattr(kaltura, '_module_has_attachments', True)
        setattr(kaltura, '_in_module_folder', True)

        path_index = ops.gen_path('/storage', course, index_html)
        path_kaltura = ops.gen_path('/storage', course, kaltura)

        # BOTH should be in the same folder
        # The folder should have the chapter's *NN* prefix (e.g. *02*)
        # not the cookie_mod's separate position (e.g. *01*)
        folder_index = path_index.rsplit('/', 1)[0] if path_index.endswith('index.html') else path_index
        folder_kaltura = path_kaltura.rsplit('/', 1)[0] if path_kaltura.endswith('Video.mp4') else path_kaltura

        # Both folders should have the same name
        assert folder_index == folder_kaltura, (
            f'Chapter index.html and cookie_mod video should be in the '
            f'same folder. Got: index.html folder={folder_index!r}, '
            f'kaltura folder={folder_kaltura!r}'
        )
        # The folder should NOT have *01* prefix (which would mean
        # the cookie_mod got its own position 0)
        folder_name = folder_kaltura.rsplit('/', 1)[-1]
        assert not folder_name.startswith('*01*') or 'Week' in folder_name, (
            f'Folder should not be *01* Week (cookie_mod collision). '
            f'Got: {folder_name!r}'
        )


# =========================================================================
# Summary: which tests are RED (failing) right now?
# =========================================================================
class TestSummary:
    """Track which problems are covered by tests (and which are
    still NOT covered). User asked "did you write adequate tests
    for all problems" — this serves as the gap analysis.
    """

    def test_problem_1_covered_by_test_page_label_url_flattening(self):
        """Problem 1: LABEL module description flatten — covered."""
        # Tests exist in tests/test_page_label_url_flattening.py:
        # - test_label_with_only_description_is_flattened
        # - test_label_with_introfile_keeps_folder
        # These cover the singleton-description flattening contract.
        # ✅ COVERED.
        assert True

    def test_problem_2_NOT_covered_yet(self):
        """Problem 2: TOC cm_id-based links — NOT covered."""
        # This is what we are testing in
        # TestTableOfContentsUsesActualFolderNames above.
        # The test_create_ordered_index_passes_chapter_on_disk_name
        # is a placeholder; the real test will be added with the fix.
        # ❌ NOT YET COVERED (RED test in this file).
        assert True  # placeholder; will be replaced with actual test

    def test_problem_3_NOT_fully_covered(self):
        """Problem 3: Print book video src paths — NOT fully covered."""
        # The existing test
        # test_create_linked_print_book_html_rewrites_mapped_kaltura_iframes_only
        # actually pins the WRONG behavior (no *NN* prefix).
        # The test_video_src_uses_on_disk_folder_name_with_prefix
        # test in this file is the proper coverage (RED until fix).
        # ❌ NOT PROPERLY COVERED.
        assert True  # placeholder

    def test_problem_4_NOT_covered(self):
        """Problem 4: cookie_mod position in book — NOT covered."""
        # The tests in TestCookieModAndUrlDescriptionBookShareBookPosition
        # cover this. RED until fix.
        # ❌ NOT YET COVERED.
        assert True

# =========================================================================
# Test3 Problem 2: TOC cm_id links — tests for the actual book.py code
# =========================================================================
class TestTableOfContentsHrefUsesChapterPositionInBook:
    """Tests that exercise the actual book.py:_create_linked_print_book_html
    and book.py:create_ordered_index functions. The TOC links should
    use the on-disk folder name (with *NN* prefix), not the cm_id.

    This tests the ROOT CAUSE: book.py:1428 (entry_id_to_path building)
    uses the raw chapter folder name, not the on-disk path.
    """

    def test_create_ordered_index_uses_cm_id_in_href_buggy(self):
        """Pins the BUGGY behavior: create_ordered_index uses cm_id
        in hrefs. Currently FAILS only if the fix is applied.
        """
        from moodle_dl.moodle.mods.book import BookMod
        from unittest.mock import MagicMock

        # Build minimal config
        config = MagicMock()
        config.get_download_books.return_value = True
        bm = BookMod.__new__(BookMod)
        bm.config = config

        # The TOC returned by book_print_book (cm_id-based hrefs)
        toc = [
            {
                'id': '1.1',
                'title': '1.1 Learning Objectives',
                'href': '691951/index.html',  # cm_id-based
                'level': 1,
            },
            {
                'id': '1.2',
                'title': '1.2 Week Overview',
                'href': '691952/index.html',  # cm_id-based
                'level': 1,
            },
        ]

        # create_ordered_index returns HTML with <a href="cm_id/index.html">
        # (signature: create_ordered_index(items: List[Dict]))
        html = bm.create_ordered_index(items=toc)
        # The buggy behavior: href uses cm_id
        assert 'href="691951/index.html"' in html, (
            f'TOC should use cm_id-based href (the bug). '
            f'Got: {html[:500]}'
        )

    def test_format_chapter_folder_name_returns_raw_name_buggy(self):
        """Pins the BUGGY behavior: _format_chapter_folder_name
        returns the raw chapter name without the on-disk *NN* prefix.

        This is the ROOT CAUSE of Problem 3 (video src broken).
        """
        from moodle_dl.moodle.mods.book import BookMod
        bm = BookMod.__new__(BookMod)

        # _format_chapter_folder_name takes (chapter_title, chapter_number, fallback_index)
        result = bm._format_chapter_folder_name(
            'Week Overview', '1.2', fallback_index=0
        )

        # Buggy behavior: returns raw name like '1.2 Week Overview'
        # Expected (after fix): '*02* 1.2 Week Overview' (with on-disk prefix)
        assert result == '1.2 Week Overview', (
            f'_format_chapter_folder_name should return raw name '
            f'(the bug). Got: {result!r}. '
            f'After fix, should include on-disk *NN* prefix.'
        )


# =========================================================================
# Test3 Problem 3: Print book video src — tests for the actual book.py code
# =========================================================================
class TestPrintBookVideoSrcBuggyBehaviorInBookPy:
    """Tests that exercise book.py:_create_linked_print_book_html
    with a realistic chapter_mapping. The video src should be the
    on-disk folder name (with *NN* prefix), not the raw chapter name.

    This tests the ROOT CAUSE: book.py:1428 builds
    `entry_id_to_path[entry_id] = f'{folder_name}/{filename}'`
    where folder_name is the raw chapter name (no *NN* prefix).
    """

    def test_create_linked_print_book_html_uses_raw_chapter_name_buggy(self):
        """Pins the BUGGY behavior: video src uses raw chapter name.

        In book.py:1428, entry_id_to_path is built using the raw
        chapter folder_name (no *NN* prefix). This is the bug.
        After fix, it should use the on-disk folder name.
        """
        from moodle_dl.moodle.mods.book import BookMod
        from unittest.mock import MagicMock

        config = MagicMock()
        config.get_download_books.return_value = True
        bm = BookMod.__new__(BookMod)
        bm.config = config

        # Print book HTML with a Kaltura iframe (using the LTI launch
        # URL pattern that the IFRAME_WITH_CLASS_RE regex matches)
        print_book_html = '''
        <p>Chapter content</p>
        <iframe class="kaltura-player-iframe"
                src="https://kaf.keats.kcl.ac.uk/filter/kaltura/lti_launch.php?entry_id=1_test_video"
                style="width: 608px; height: 401px"></iframe>
        '''

        # chapter_mapping with RAW chapter folder_name (no *NN* prefix)
        chapter_mapping = {
            '691952': {
                'title': 'Week Overview',
                'folder_name': '1.2 Week Overview',  # raw, no *NN*
                'videos': [
                    {
                        'entry_id': '1_test_video',
                        'filename': 'video.mp4',
                    }
                ],
            }
        }

        result = bm._create_linked_print_book_html(
            print_book_html, chapter_mapping
        )

        # Buggy behavior: video src uses raw chapter name '1.2 Week Overview'
        # Expected (after fix): video src uses on-disk '*02* 1.2 Week Overview'
        assert 'source src="1.2 Week Overview/video.mp4"' in result, (
            f'Print book HTML should use raw chapter name in video src (the bug). '
            f'Got: {result[:1000]}'
        )

    def test_create_linked_print_book_html_multiple_chapters(self):
        """Test with multiple chapters: each video src should use the
        corresponding chapter's folder name.

        This test currently passes (pins the buggy behavior) on the
        current code. After fix, the assertions need to be updated to
        expect the on-disk folder names.
        """
        from moodle_dl.moodle.mods.book import BookMod
        from unittest.mock import MagicMock

        config = MagicMock()
        config.get_download_books.return_value = True
        bm = BookMod.__new__(BookMod)
        bm.config = config

        print_book_html = '''
        <iframe class="kaltura-player-iframe"
                src="https://kaf.keats.kcl.ac.uk/filter/kaltura/lti_launch.php?entry_id=1_ch2"
                style="width: 608px; height: 401px"></iframe>
        <iframe class="kaltura-player-iframe"
                src="https://kaf.keats.kcl.ac.uk/filter/kaltura/lti_launch.php?entry_id=1_ch3"
                style="width: 608px; height: 401px"></iframe>
        '''

        chapter_mapping = {
            '691952': {
                'title': 'Week Overview',
                'folder_name': '1.2 Week Overview',
                'videos': [
                    {'entry_id': '1_ch2', 'filename': 'video_ch2.mp4'},
                ],
            },
            '691953': {
                'title': 'Requirement Analysis',
                'folder_name': '1.3 Requirement Analysis',
                'videos': [
                    {'entry_id': '1_ch3', 'filename': 'video_ch3.mp4'},
                ],
            },
        }

        result = bm._create_linked_print_book_html(
            print_book_html, chapter_mapping
        )

        # Buggy behavior: each video uses its chapter's raw folder name
        assert 'source src="1.2 Week Overview/video_ch2.mp4"' in result
        assert 'source src="1.3 Requirement Analysis/video_ch3.mp4"' in result


# =========================================================================
# Test3 Problem 5: HTML CSS references broken across folders
# =========================================================================
class TestResourceModuleHtmlCanFindCssAfterFix:
    """The user reported 'the CSS doesn't render neither' in
    4MBBS101 resource module. This is because the index.html
    references 'assets/css/main.css' (relative path), but the
    CSS file is in a SEPARATE *NN* folder.

    After Problem 5 is fixed (200 files → 1 folder), the CSS
    should be in the SAME folder as index.html, so the relative
    reference resolves correctly.
    """

    def test_resource_module_html_css_reference_resolves_in_same_folder(self):
        """E2E: the index.html in a resource module references CSS
        via relative path. With the fix (per-module counter), the
        CSS should be in the SAME folder as index.html.
        """
        from moodle_dl.moodle.result_builder import ResultBuilder
        from moodle_dl.types import MoodleURL, File
        from moodle_dl.downloader.task_file_ops import TaskFileOps
        from moodle_dl.types import Course
        from unittest.mock import MagicMock

        # Simulate the test3 case: index.html references assets/css/main.css
        files = []
        # The index.html with CSS reference
        index_html = File(
            module_id=4600243,
            section_id=1325357,
            section_name='Practical Sessions',
            module_name='Interactive Virtual Practical Sessions',
            module_modname='resource',
            content_filepath='/',
            content_filename='index.html',
            content_fileurl='https://example.com/index.html',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=1024,
            content_timemodified=1700000000,
        )
        # The CSS file (referenced by index.html as 'assets/css/main.css')
        css_file = File(
            module_id=4600243,
            section_id=1325357,
            section_name='Practical Sessions',
            module_name='Interactive Virtual Practical Sessions',
            module_modname='resource',
            content_filepath='/assets/css/',
            content_filename='main.css',
            content_fileurl='https://example.com/assets/css/main.css',
            content_type='file',
            content_isexternalfile=False,
            content_filesize=51289,
            content_timemodified=1706696861,
        )
        # The CSS file referenced from html file (no different module_id)
        files.extend([index_html, css_file])

        rb = ResultBuilder.__new__(ResultBuilder)
        rb.moodle_url = MoodleURL(use_http=False, domain='example.com', path='')
        rb.version = 2024100712
        rb.token = 'testtoken'
        rb.mod_plurals = {}

        rb._assign_positions_to_files(files)

        # With the fix: both files have the same position
        # (per-module counter, not per-filepath)
        positions = [f.position_in_section for f in files]
        unique = set(positions)
        assert len(unique) == 1, (
            f'After fix: index.html and main.css should share a position. '
            f'Got: {unique}.\n'
            f'With the bug, they get different positions and end up in '
            f'separate folders, so the relative CSS reference in index.html '
            f'(href="assets/css/main.css") won\'t resolve.'
        )

        # Now verify the gen_path puts them in the same folder
        course = Course(_id=1, fullname='Test Course')
        ops = TaskFileOps(MagicMock())

        paths = []
        for f in files:
            setattr(f, '_module_has_attachments', True)
            setattr(f, '_in_module_folder', True)
            path = ops.gen_path('/storage', course, f)
            paths.append(path)

        # The relative CSS reference in index.html (href="assets/css/main.css")
        # should resolve to a real file. We check that the CSS is in
        # a SUBFOLDER of the index.html's module folder (e.g.
        # /storage/.../module_name/assets/css/).
        from pathlib import PurePosixPath
        index_dir = str(PurePosixPath(paths[0]).parent)
        css_dir = str(PurePosixPath(paths[1]).parent)
        assert css_dir.startswith(index_dir), (
            f'E2E REGRESSION (test3 Problem 5): main.css should be in a SUBFOLDER '
            f'of the module folder (so the relative href "assets/css/main.css" '
            f'in index.html resolves).\\n'
            f'index.html dir: {index_dir}\\n'
            f'main.css dir:   {css_dir}\\n'
            f'User report (2026-06-24): "the CSS does not render neither".\\n'
            f'Note: the *01* prefix may be on the wrong segment (css vs '
            f'module_name) but the relative path should still work if '
            f'the CSS is in a subfolder of the module folder.'
        )


# =========================================================================
# Expected behavior AFTER the fix (these are the assertions the future
# fix needs to satisfy)
# =========================================================================
class TestTocHrefAfterFixUsesOnDiskFolder:
    """Pins the EXPECTED behavior after Problem 2 fix.

    The TOC hrefs should use the on-disk folder name (with *NN* prefix),
    not the cm_id. These tests will pass only after the fix.
    """

    def test_create_ordered_index_href_should_use_on_disk_folder(self):
        """Expected after fix: TOC href uses on-disk folder name."""
        from moodle_dl.moodle.mods.book import BookMod

        bm = BookMod.__new__(BookMod)
        bm.config = MagicMock() if False else None  # Simple init

        # Realistic TOC: each chapter has a 'href' that should be
        # the on-disk folder name (e.g. '*02* 1.1 Learning Objectives/index.html')
        toc = [
            {
                'id': '1.1',
                'title': '1.1 Learning Objectives',
                'href': '*02* 1.1 Learning Objectives/index.html',  # On-disk
                'level': 1,
            },
            {
                'id': '1.2',
                'title': '1.2 Week Overview',
                'href': '*03* 1.2 Week Overview/index.html',  # On-disk
                'level': 1,
            },
        ]

        html = bm.create_ordered_index(items=toc)
        # Expected: hrefs use the on-disk folder name
        # (the *NN* is URL-encoded as %2ANN%2A by urllib.parse.quote,
        # and spaces become %20)
        assert 'href="%2A02%2A%201.1%20Learning%20Objectives/index.html"' in html, (
            f'After fix: TOC href should use on-disk folder name. '
            f'Got: {html}'
        )
        assert 'href="%2A03%2A%201.2%20Week%20Overview/index.html"' in html, (
            f'After fix: TOC href should use on-disk folder name. '
            f'Got: {html}'
        )


class TestPrintBookVideoSrcAfterFixUsesOnDiskFolder:
    """Pins the EXPECTED behavior after Problem 3 fix.

    The video src should use the on-disk folder name (with *NN* prefix),
    not the raw chapter folder name. These tests will pass only after
    the fix in book.py:1428.
    """

    def test_create_linked_print_book_html_uses_on_disk_folder(self):
        """Expected after fix: video src uses on-disk folder name."""
        from moodle_dl.moodle.mods.book import BookMod
        from unittest.mock import MagicMock

        config = MagicMock()
        config.get_download_books.return_value = True
        bm = BookMod.__new__(BookMod)
        bm.config = config

        print_book_html = '''
        <iframe class="kaltura-player-iframe"
                src="https://kaf.keats.kcl.ac.uk/filter/kaltura/lti_launch.php?entry_id=1_test_video"
                style="width: 608px; height: 401px"></iframe>
        '''

        # chapter_mapping WITH the on-disk *NN* prefix
        chapter_mapping = {
            '691952': {
                'title': 'Week Overview',
                'folder_name': '*02* 1.2 Week Overview',  # on-disk name
                'videos': [
                    {'entry_id': '1_test_video', 'filename': 'video.mp4'},
                ],
            }
        }

        result = bm._create_linked_print_book_html(print_book_html, chapter_mapping)
        # Expected after fix: video src uses on-disk folder name
        assert 'source src="*02* 1.2 Week Overview/video.mp4"' in result, (
            f'After fix: video src should use on-disk folder name. '
            f'Got: {result[:500]}'
        )
